### ISSUE TITLE
online demo?

### ISSUE THREAD

**Issue by MaxBittker** [wwwtyro/vixel#2]
I would love to see one of these examples running on a static site. 
Is there already such a thing online somewhere?
No pressure if not though, just opening this issue for tracking.

awesome project!

**Comment by wwwtyro** [comment]
Hi! Yes, you can see it in action here: https://wwwtyro.github.io/vixel-editor/

**Comment by MaxBittker** [comment]
wow! really great demo, thanks :)

**Comment by MaxBittker** [comment]
the painterly way the samples fill in is very interesting

**Comment by valentinbdv** [comment]
> Hi! Yes, you can see it in action here: https://wwwtyro.github.io/vixel-editor/

You should definitely put that in the readme! ;)

**Comment by arthurwolf** [comment]
The "rotate camera" with right mouse button + drag, is extremely odd/weird/impractical. Am I missing something here, doing something wrong? I can't get it to do anything I want, I get into very odd positions, it doesn't work like *any* 3D software I've ever used before. What's going on here? Any help appreciated.
