### ISSUE TITLE
Vixel not working on iOS

### ISSUE THREAD

**Issue by ehouais** [wwwtyro/vixel#6]
Hello, this project is awesome, and I use it to render .vox files in Observable notebooks (https://observablehq.com/@ehouais/rendering-vox-files-with-vixel).
It doesn't seem to work on iOS Safari, though. Do you have any idea why ?

**Comment by wwwtyro** [comment]
Taking a look :+1:

**Comment by wwwtyro** [comment]
Can you give this another shot with version 1.0.2?

**Comment by ehouais** [comment]
Works like a charm now ! I still have issues with touch events, but that is another story... Thanks a lot !

**Comment by wwwtyro** [comment]
That's great to hear, thanks!
